# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180125_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to=b'teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
